curve_goi <- list(

  cnv=c(
    "ALK","AR","AURKA","BRAF","CCND1", "CCND3","CCNE1", "CDK4","EGFR","ERBB2","FGFR1","FGFR2","FGFR3",
    "FOXP1","IDH1","IDH2","KDR", "KIT","KRAS","MAPK1","MDM2","MET", "MYC","MYCN", "NCOA3","NOTCH1","NOTCH2",
    "NRAS", "PDGFRA","PDGFRB","PIK3CA","PIK3CB", "RAF1","VEGFA","TP53","BRCA1","BRCA2","CDKN2A", "CDKN2B",
    "NF1","PTEN","RB1", "ATM","APC","MSH2","MLH1"),

  germline=c(
    "AIP","AKT1","ALK","APC","ATM","ATR","AURKA","AXIN2","BABAM1","BAP1","BARD1","BLM","BMPR1A","BRAF",
    "BRCA1","BRCA2","BRIP1","BUB1B","CASP8","CBL","CCND1","CDC73","CDH1","CDK4","CDKN1B","CDKN1C","CDKN2A",
    "CEBPA","CHEK1","CHEK2","COL17A1","COL7A1","CTNNA1","CYLD","CYP21A2","DDB2","DICER1","DKC1","EGFR",
    "ELANE","EPCAM","EPHB2","ERCC1","ERCC2","ERCC3","ERCC4","ERCC5","ETV6","EXT1","EXT2","FAM175A","FANCA",
    "FANCB","FANCC","FANCD2","FANCE","FANCF","FANCG","FANCI","FANCL","FANCM","FAS","FASLG","FH","FLCN",
    "G6PC3","GALNT12","GATA2","GEN1","GFI1","GPC3","GREM1","HAX1","HOXB13","HOXD4","HRAS","IDH1","IDH2",
    "IGF1","IGF2","JAK2","KIF1B","KIT","KLLN","KRAS","LAMA3","LAMB3","LAMC2","MAP2K1","MAP2K2","MAX","MC1R",
    "MEN1","MET","MITF","MLH1","MLH3","MPL","MRE11A","MSH2","MSH3","MSH6","MSR1","MUTYH","NBN","NF1","NF2",
    "NHP2","NOP10","NRAS","NSD1","NTRK1","ODC1","PALB2","PALLD","PARK2","PAX5","PDGFRA","PDGFRB","PHB",
    "PHOX2B","PIK3CA","PLA2G2A","PMS1","PMS2","POLD1","POLE","POU6F2","PPARG","PPM1D","PRKAR1A","PRSS1",
    "PTCH1","PTCH2","PTEN","PTPN11","PTPRJ","RAD50","RAD51","RAD51B","RAD51C","RAD51D","RAD54L","RAF1",
    "RB1","RECQL4","RET","RNASEL","RUNX1","SBDS","SDHA","SDHAF2","SDHB","SDHC","SDHD","SH2B3","SH2D1A",
    "SHOC2","SLC26A4","SLX4","SMAD4","SMAD7","SMARCA4","SMARCB1","SOS1","SPRED1","STK11","SUFU","TERC",
    "TERT","TGFB1","TGFBR1","TGFBR2","THPO","TINF2","TLR2","TLR4","TMC6","TMC8","TMEM127","TP53","TP53BP1",
    "TSC1","TSC2","UIMC1","USB1","VHL","WAS","WRN","WT1","XPA","XPC","XRCC2")

)
